### ISSUE TITLE
是否可针对特定后缀进行自动空格😆

### ISSUE THREAD

**Issue by leidichen** [halfcrazy/vscode-pangu#6]
pangu 空格插件 VSCODE 中有好几个，但你设计的这一款独具匠心的插件，可设置保存时自动空格，但会作用于全局文件。是否可以针对特定文件，例如自动保存模式只针对于 .md 结尾的文件。

**Comment by halfcrazy** [comment]
Done. 你可以试下0.1.5版本，引入了 auto_space_on_save_ext 配置，可以配指定后缀。例如
"auto_space_on_save_ext": [".md", ".txt"],

**Comment by leidichen** [comment]
更新插件及配置后，成功实现指定后缀文件保存后自动空格，十分感谢！
